[package]
name = "windowvec"
version = "0.0.0"
description = "A fixed-size array that supports push operations and discards old data"
authors = ["Michele Lacchia <michelelacchia@gmail.com>"]
edition = "2018"
license = "ISC"

[dependencies]
